// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhanSuWebAPI.Models.Context;

#nullable disable

namespace NhanSuWebAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NhanSuWebAPI.Models.BangLuong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<decimal>("BHTN_DN")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BHTN_NLD")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BHXH_DN")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BHXH_NLD")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BHYT_DN")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BHYT_NLD")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("LuongCB")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("LuongThucLanh")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("ThueTNCN")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongPhat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongPhuCap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongTU")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongThuNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongThuong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongTienTC")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaLuong");

                    b.HasIndex("MaNV");

                    b.ToTable("BangLuong");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.ChamCong", b =>
                {
                    b.Property<int>("MaCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCC"));

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayChamCong")
                        .HasColumnType("datetime2");

                    b.Property<float>("SoGioLam")
                        .HasColumnType("real");

                    b.Property<float>("SoGioTC")
                        .HasColumnType("real");

                    b.Property<TimeSpan?>("ThoiGianRa")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ThoiGianVao")
                        .HasColumnType("time");

                    b.Property<string>("TrangThaiCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCC");

                    b.HasIndex("MaNV");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.ChinhSach", b =>
                {
                    b.Property<int>("MaCS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCS"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiCS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaCS");

                    b.HasIndex("MaNV");

                    b.ToTable("ChinhSach");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.ChucVu", b =>
                {
                    b.Property<int>("MaCV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCV"));

                    b.Property<string>("TenCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCV");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.HopDong", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LuongCB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaLoaiHD")
                        .HasColumnType("int");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHD");

                    b.HasIndex("MaLoaiHD");

                    b.HasIndex("MaNV");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.LoaiHD", b =>
                {
                    b.Property<int>("MaLoaiHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiHD"));

                    b.Property<string>("TenLoaiHD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiHD");

                    b.ToTable("LoaiHD");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.NgayLe", b =>
                {
                    b.Property<int>("MaNL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNL"));

                    b.Property<DateTime>("NgayBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKT")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNgayLe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNL");

                    b.ToTable("NgayLe");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.NghiPhep", b =>
                {
                    b.Property<int>("MaNP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNP"));

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiNP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SoNgayNghiCoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNP");

                    b.HasIndex("MaNV");

                    b.ToTable("NghiPhep");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanToc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCV")
                        .HasColumnType("int");

                    b.Property<int>("MaPB")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiSinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonGiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaCV");

                    b.HasIndex("MaPB");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.PhongBan", b =>
                {
                    b.Property<int>("MaPB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPB"));

                    b.Property<string>("TenPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPB");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.PhuCap", b =>
                {
                    b.Property<int>("MaPC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPC"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiPC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPC");

                    b.HasIndex("MaNV");

                    b.ToTable("PhuCap");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaQuyen");

                    b.ToTable("Quyen");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTK");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaQuyen");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.TamUng", b =>
                {
                    b.Property<int>("MaTU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTU"));

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTamUng")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTU");

                    b.HasIndex("MaNV");

                    b.ToTable("TamUng");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.TongHopCong", b =>
                {
                    b.Property<int>("MaTH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTH"));

                    b.Property<float>("LamNgayLe")
                        .HasColumnType("real");

                    b.Property<float>("LamNgayNghi")
                        .HasColumnType("real");

                    b.Property<float>("LamThemNgayThuong")
                        .HasColumnType("real");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayCong")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayNghiCoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayNghiKhongLuong")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<float>("TongGioLamThucTe")
                        .HasColumnType("real");

                    b.HasKey("MaTH");

                    b.HasIndex("MaNV");

                    b.ToTable("TongHopCong");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.BangLuong", b =>
                {
                    b.HasOne("NhanSuWebAPI.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.ChamCong", b =>
                {
                    b.HasOne("NhanSuWebAPI.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.ChinhSach", b =>
                {
                    b.HasOne("NhanSuWebAPI.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.HopDong", b =>
                {
                    b.HasOne("NhanSuWebAPI.Models.LoaiHD", "LoaiHD")
                        .WithMany()
                        .HasForeignKey("MaLoaiHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhanSuWebAPI.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHD");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.NghiPhep", b =>
                {
                    b.HasOne("NhanSuWebAPI.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.NhanVien", b =>
                {
                    b.HasOne("NhanSuWebAPI.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("MaCV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhanSuWebAPI.Models.PhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("MaPB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.PhuCap", b =>
                {
                    b.HasOne("NhanSuWebAPI.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.TaiKhoan", b =>
                {
                    b.HasOne("NhanSuWebAPI.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhanSuWebAPI.Models.Quyen", "Quyen")
                        .WithMany()
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.TamUng", b =>
                {
                    b.HasOne("NhanSuWebAPI.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhanSuWebAPI.Models.TongHopCong", b =>
                {
                    b.HasOne("NhanSuWebAPI.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
